-
  name: Install Nginx
  hosts: all
  become: true
  tasks:
    - name: Install Nginx on Debian
      apt:
        name: nginx
        state: present
      when: ansible_os_family == 'Debian'
    
    - name: Install Nginx on Redhat
      yum:
        name: nginx
        state: present
      when: ansible_os_family == 'Redhat'


# Conditinoal & Register
-
  name: Check service status and Email if Down
  hosts: localhost
  become: true
  tasks:
    - command: service httpd status
      register: result
    
    - mail:
        to: admin@organization.com
        subject: Service Down
        body: Httpd service is Down
        when: result.stdout.find('down') != -1
    
    - debug:
        msg: Httd Service is Down
        when: result.stdout.find('down') != -1
    
    - debug:
        msg: Httd Service is Up
        when: result.stdout.find('down') == -1

  
  # Lab: Start service on target1 only
---
-  name: 'Start service'
   hosts: all
   become: yes
   tasks:
     -  service: 'name=nginx state=started'
        when: 'ansible_host == "target1"'

# Lab: Print age with condition
---
- name: 'Am I an Adult or a Child?'
  hosts: localhost
  vars:
    age: 25
  tasks:
    - name: I am a Child
      command: 'echo "I am a Child"'
      when: 'age < 18'
    - name: I am an Adult
      command: 'echo "I am an Adult"'
      when: 'age >= 18'

# Lab: Playbook /home/bob/playbooks/nameserver.yaml attempts to add an entry in /etc/resolv.conf file to add a new nameserver.
The first task in the playbook is using the shell module to display the existing contents of /etc/resolv.conf file and the second one is adding a new line containing the name server details into the file. However, when this playbook is run multiple times, it keeps adding new entries of same line into the resolv.conf file. To resolve this issue, update the playbook as per details mentioned below.

Add a register directive to store the output of the first task to a variable called command_output
Then add a conditional to the second task to check if the output already contains the name server (10.0.250.10). Use command_output.stdout.find(<IP>) == -1
Note:
a. A better way to do this would be to use the lineinfile module. This is just for practice.
b.shell and command modules are similar in a way that they are used to execute a command on the system. However, shell executes the command inside a shell giving us access to environment variables and redirection using >>.

---
- name: 'Add name server entry if not already entered'
  hosts: localhost
  become: yes
  tasks:
    - shell: 'cat /etc/resolv.conf'
      register: command_output
    - shell: 'echo "nameserver 10.0.250.10" >> /etc/resolv.conf'
      when: 'command_output.stdout.find("10.0.250.10") == -1'